[world]
name = "fight_club"
description = "Fight Club game world"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo"
seed = "fight_club"

[world.socials]
x = "https://twitter.com/dojostarknet"

[namespace]
default = "fight_club"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x5fb6a787e28695a1c4938b99d2669e04ba7076e352d5202a7ee5d16006da40f"
private_key = "0x01b150b2415216608449408559685434cd8cbf4e786602fef9db5db8e621b825"

[writers]
"fight_club" = ["fight_club-actions"]
