# The World address to index.
world_address = "0x03860cfcc70837fb5623b649ca38cd597c7fca80e920e94f8c433931b788ba32"
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/fightclubslot/katana"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true
