/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef, useMemo } from "react";
import { SkeletonUtils } from "three-stdlib";
import { useCharacterAnimations } from "../contexts/CharacterAnimations";

function Woman(props) {
  const group = useRef();
  const { scene, animations } = useGLTF("./models/woman.gltf");
  const { setAnimations, animationIndex, animations: contextAnimations } = useCharacterAnimations();
  
  // Clone the scene to create independent instances
  const clonedScene = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    if (contextAnimations.length === 0) {
      setAnimations(names);
    }
  }, [names, contextAnimations.length, setAnimations]);

  useEffect(() => {
    if (actions && names[animationIndex]) {
      actions[names[animationIndex]].reset().fadeIn(0.5).play();
      return () => {
        if (actions[names[animationIndex]]) {
          actions[names[animationIndex]].fadeOut(0.5);
        }
      };
    }
  }, [animationIndex, actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={clonedScene} />
    </group>
  );
}

useGLTF.preload("./models/woman.gltf");

export default Woman;
